service: AddressBook-test
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  addressBook:
    handler: index.handler
    events:
      - http: 
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true